/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 09 21:36:22 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board(0L);
      Board board1 = new Board(board0);
      board1.isWinningBoard();
      board1.isFull();
      board1.hasEmptyCells();
      Random.setNextRandom(4);
      board0.toString();
      board0.hashCode();
      board0.getScore();
      board0.isFull();
      board1.hasEmptyCells();
      board0.isLosingBoard();
      board0.moveDown();
      board1.moveUp();
      board0.toString();
      Random.setNextRandom(0);
      board1.toString();
      board0.moveUp();
      board1.getEmptyPositions();
      board0.moveUp();
      board1.getCell(1, 3);
      board1.equals(board0);
      board0.equals((Object) null);
      board1.isLosingBoard();
      board0.getScore();
      Random.setNextRandom(1);
      board0.getCell(1, 1);
      board1.getEmptyPositions();
      board0.moveRight();
      board0.toString();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board(23);
      board0.moveRight();
      board0.getEmptyPositions();
      board0.isFull();
      board0.isFull();
      board0.isWinningBoard();
      board0.isFull();
      board0.toString();
      board0.repOk();
      board0.moveLeft();
      board0.moveUp();
      board0.hasEmptyCells();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.toString();
      board0.isLosingBoard();
      Board.Direction.values();
      // Undeclared exception!
      board0.toString();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board(2);
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.moveRight();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.moveLeft();
      board0.isFull();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("A(iD'I]<>>>.q{");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.A(iD'I]<>>>.q{
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveRight();
      board0.getEmptyPositions();
      board0.isFull();
      board0.isFull();
      board0.isFull();
      board0.moveRight();
      board0.toString();
      board0.repOk();
      board0.moveLeft();
      board0.moveUp();
      board0.hasEmptyCells();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.toString();
      board0.isLosingBoard();
      Board.Direction.values();
      board0.toString();
      board0.getSize();
      board0.isLosingBoard();
      board0.moveDown();
      board0.repOk();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board(2);
      board0.getEmptyPositions();
      board0.moveRight();
      board0.moveRight();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.repOk();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("A(iD'I]<>>>.q{");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.A(iD'I]<>>>.q{
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(56);
      board0.toString();
      // Undeclared exception!
      board0.moveRight();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      board0.isFull();
      board0.moveRight();
      Board board1 = new Board(board0);
      board1.toString();
      board1.hasEmptyCells();
      board1.hashCode();
      board1.moveUp();
      board0.hasEmptyCells();
      board1.isWinningBoard();
      board1.toString();
      board1.moveLeft();
      board1.isLosingBoard();
      board1.isWinningBoard();
      board0.moveDown();
      Board.Position board_Position0 = new Board.Position((-4133), 4);
      Board.Position board_Position1 = new Board.Position((-4133), 2082);
      board_Position0.equals(board_Position1);
      board0.getSize();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board(25);
      board0.toString();
      board0.moveRight();
      Board board1 = new Board(board0);
      board1.toString();
      board1.hasEmptyCells();
      board1.hashCode();
      board0.hasEmptyCells();
      board1.isWinningBoard();
      board0.moveDown();
      board1.toString();
      board1.moveLeft();
      board1.isLosingBoard();
      // Undeclared exception!
      board1.moveUp();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board(0L);
      board0.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(4, 810);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(4, 810);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      board0.moveLeft();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.getCell((-1276), 3927);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1276, 3927) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1235, (-3));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Object object0 = new Object();
      board_Position0.equals(object0);
      Board.Direction.values();
      Board board0 = new Board();
      board0.moveLeft();
      board0.isFull();
      board0.moveDown();
      Random.setNextRandom(4);
      board0.moveDown();
      board0.moveRight();
      assertEquals(4, board0.getScore());
      
      Board.Position board_Position1 = new Board.Position(1235, (-3));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      boolean boolean0 = board0.moveRight();
      assertFalse(boolean0);
      
      Board board1 = new Board(board0);
      board1.toString();
      board1.hasEmptyCells();
      board1.hashCode();
      board0.hasEmptyCells();
      boolean boolean1 = board1.isWinningBoard();
      board0.getEmptyPositions();
      boolean boolean2 = board0.moveDown();
      String string0 = board1.toString();
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      
      boolean boolean3 = board1.moveLeft();
      assertTrue(boolean3 == boolean1);
      
      boolean boolean4 = board1.isLosingBoard();
      assertFalse(boolean4 == boolean2);
      assertTrue(boolean4);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(941, (-372));
      board_Position1.toString();
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      board_Position0.toString();
      Board board0 = new Board(4);
      board0.moveUp();
      board0.moveDown();
      board0.toString();
      board_Position0.toString();
      board0.isLosingBoard();
      board0.isWinningBoard();
      board0.moveDown();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("(4, 4)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.(4, 4)
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      boolean boolean0 = board0.moveRight();
      Board board1 = new Board(board0);
      board1.toString();
      board0.isFull();
      board0.hasEmptyCells();
      board1.hashCode();
      board0.hasEmptyCells();
      boolean boolean1 = board0.moveDown();
      assertFalse(boolean1);
      
      String string0 = board1.toString();
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      
      boolean boolean2 = board1.moveLeft();
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOk());
      
      board0.isFull();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.repOk();
      board0.toString();
      Cell cell0 = new Cell(2048);
      board0.setCell(2, 2, cell0);
      board0.moveDown();
      board0.moveUp();
      board0.isFull();
      Object object0 = new Object();
      board0.isFull();
      board0.isFull();
      board0.toString();
      board0.moveLeft();
      board0.equals(set0);
      board0.moveRight();
      Board.Position board_Position0 = new Board.Position((-97), 0);
      board0.hasEmptyCells();
      board0.moveLeft();
      board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.getSize();
      board0.hasEmptyCells();
      assertTrue(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      board0.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(4, 810);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals(board_Position0);
      board0.moveLeft();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.getCell((-1276), 3927);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1276, 3927) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      board0.isFull();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.toString();
      board0.repOk();
      board0.moveDown();
      board0.hashCode();
      board0.isFull();
      Board.Position board_Position0 = new Board.Position(24, 24);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.getSize();
      Random.setNextRandom((-1579));
      board0.moveRight();
      board0.getSize();
      board0.getEmptyPositions();
      board0.moveDown();
      board0.getScore();
      // Undeclared exception!
      try { 
        board0.getCell(4, 485);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 485) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2110), (-2110));
      boolean boolean0 = board_Position0.equals((Object) null);
      assertEquals((-2110), board_Position0.col);
      assertFalse(boolean0);
      assertEquals((-2110), board_Position0.row);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int int0 = 3;
      Board board0 = new Board(3);
      board0.moveDown();
      board0.moveUp();
      // Undeclared exception!
      try { 
        board0.getCell(0, 3);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 3) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      board0.isLosingBoard();
      Board.Position board_Position0 = new Board.Position((-1508), 0);
      board_Position0.toString();
      board_Position0.toString();
      board0.isLosingBoard();
      board0.toString();
      board0.toString();
      board_Position0.equals("     ");
      board0.moveUp();
      board0.moveDown();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.toString();
      board0.moveLeft();
      board0.toString();
      board0.moveDown();
      board0.hashCode();
      board0.isLosingBoard();
      board0.getSize();
      board0.hasEmptyCells();
      Board board1 = new Board();
      board0.equals(board1);
      assertEquals(16, board0.getScore());
      
      boolean boolean0 = board1.isWinningBoard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2048, 1879);
      Board.Position board_Position1 = new Board.Position(470, 477);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(boolean0);
      assertEquals(470, board_Position1.row);
      assertEquals(477, board_Position1.col);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board((-699L));
      board0.hasEmptyCells();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.moveDown();
      board0.equals((Object) null);
      board0.moveLeft();
      Board.Position board_Position0 = new Board.Position(1088, 4);
      board_Position0.toString();
      board_Position0.toString();
      board0.getEmptyPositions();
      board_Position0.toString();
      board_Position0.equals(board0);
      board0.moveLeft();
      board0.repOk();
      board0.getScore();
      board0.isWinningBoard();
      board0.repOk();
      board0.hashCode();
      board0.isFull();
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.moveRight();
      board0.isFull();
      board0.hashCode();
      board0.equals(set0);
      board0.equals("(1088, 4)");
      board_Position0.toString();
      board0.hashCode();
      board0.toString();
      board_Position0.toString();
      boolean boolean0 = board0.isWinningBoard();
      assertEquals(8, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.moveUp();
      board0.isFull();
      Board board1 = new Board(board0);
      board1.equals(board0);
      board1.toString();
      board1.getEmptyPositions();
      int int0 = (-410);
      // Undeclared exception!
      try { 
        board1.getCell((-1), 803);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1, 803) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      board0.isLosingBoard();
      Board.Position board_Position0 = new Board.Position((-1508), 0);
      board_Position0.toString();
      board_Position0.toString();
      board0.isLosingBoard();
      board0.toString();
      board0.toString();
      board_Position0.equals("     ");
      board0.moveUp();
      board0.moveDown();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.toString();
      board0.moveLeft();
      board0.toString();
      board0.moveDown();
      board0.isLosingBoard();
      board0.getSize();
      board0.hasEmptyCells();
      board0.equals(board0);
      board0.isWinningBoard();
      assertEquals(16, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      board0.moveDown();
      board0.getEmptyPositions();
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.toString();
      board0.isWinningBoard();
      board0.repOk();
      Board board1 = new Board(294L);
      board1.toString();
      board0.equals(board1);
      board0.isWinningBoard();
      Board.Direction.values();
      board1.getEmptyPositions();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board(9);
      board0.isFull();
      Board board1 = new Board(board0);
      board1.moveRight();
      Board board2 = new Board((-1L));
      board0.equals(board2);
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(464, 464, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (464, 464) is out of bounds for board size 9
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board(0L);
      board0.moveLeft();
      board0.toString();
      board0.moveUp();
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position(2048, 4);
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell(0, 116);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 116) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.isFull();
      board0.moveLeft();
      Board board1 = new Board(board0);
      board1.moveLeft();
      board1.moveDown();
      board1.getEmptyPositions();
      board1.moveLeft();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(2048, (-1), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board(0L);
      board0.moveRight();
      board0.toString();
      board0.moveUp();
      board0.moveUp();
      board0.moveUp();
      board0.moveRight();
      board0.hashCode();
      board0.moveLeft();
      board0.getCell(0, 0);
      board0.moveLeft();
      board0.getSize();
      Board.Direction.values();
      // Undeclared exception!
      try { 
        board0.getCell(4, (-1305));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, -1305) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      boolean boolean0 = board0.moveRight();
      assertFalse(boolean0);
      
      Board board1 = new Board(board0);
      board1.toString();
      board1.hasEmptyCells();
      board1.hashCode();
      board0.hasEmptyCells();
      boolean boolean1 = board1.isWinningBoard();
      boolean boolean2 = board0.moveDown();
      assertTrue(boolean2 == boolean1);
      
      String string0 = board1.toString();
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      
      boolean boolean3 = board1.moveLeft();
      boolean boolean4 = board1.isLosingBoard();
      assertFalse(boolean4 == boolean3);
      assertTrue(boolean4);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, (-780));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board((long) (-780));
      board0.moveLeft();
      Board.Direction.values();
      board0.toString();
      board0.moveUp();
      board0.moveRight();
      board0.moveLeft();
      board0.hashCode();
      board0.getCell(0, 0);
      board0.getEmptyPositions();
      assertEquals(8, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isWinningBoard();
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position((-1776), (-1776));
      boolean boolean1 = board_Position0.equals(board0);
      assertEquals((-1776), board_Position0.col);
      assertFalse(boolean1);
      
      boolean boolean2 = board0.isLosingBoard();
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOk());
      assertTrue(boolean2 == boolean0);
      assertFalse(boolean2);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board(1L);
      board0.toString();
      Cell cell0 = board0.getCell(0, 0);
      board0.moveRight();
      Board.Position board_Position0 = new Board.Position(2048, 2340);
      board_Position0.toString();
      board0.equals(board_Position0);
      board0.moveLeft();
      board_Position0.equals(cell0);
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      Board board1 = new Board(board0);
      board0.getEmptyPositions();
      board1.moveRight();
      board1.getEmptyPositions();
      board1.moveUp();
      board1.moveLeft();
      board1.getSize();
      assertEquals(4, board1.getScore());
      
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board(0L);
      board0.moveLeft();
      Board.Position board_Position0 = new Board.Position(4, 1);
      board0.hasEmptyCells();
      board_Position0.toString();
      board_Position0.toString();
      board0.equals(board_Position0);
      board_Position0.toString();
      board0.isLosingBoard();
      board0.moveLeft();
      board0.getScore();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-372), (-372));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board();
      int int0 = (-3025);
      int int1 = 0;
      // Undeclared exception!
      try { 
        board0.getCell(1, (-372));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, -372) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      int int0 = 2072;
      Board board2 = new Board(board0);
      // Undeclared exception!
      try { 
        board2.getCell(4, 2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 2) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board(3);
      board0.moveUp();
      board0.moveDown();
      board0.moveUp();
      board0.isFull();
      boolean boolean0 = board0.moveDown();
      assertEquals(8, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board((-595L));
      board0.repOk();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell((-163), 747, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-163, 747) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      Object object0 = new Object();
      boolean boolean0 = board0.equals(object0);
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board((-2592L));
      int int0 = board0.getSize();
      assertEquals(4, int0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      String string0 = board_Position0.toString();
      assertEquals("(0, 0)", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.toString();
      board0.moveRight();
      board0.moveRight();
      board0.moveLeft();
      // Undeclared exception!
      try { 
        board0.getCell((-1), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      
      boolean boolean1 = board0.isLosingBoard();
      assertFalse(boolean1);
      
      Cell cell0 = new Cell(0);
      board0.setCell(0, 0, cell0);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board(4891L);
      board0.moveUp();
      board0.toString();
      board0.moveLeft();
      board0.moveUp();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board(0L);
      Board board1 = new Board(board0);
      Set<Board.Position> set0 = board1.getEmptyPositions();
      assertEquals(14, set0.size());
      assertTrue(board1.equals((Object)board0));
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      int int0 = 3264;
      Board board0 = new Board(3264);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board board0 = new Board(2066L);
      Board board1 = new Board(board0);
      board1.getScore();
      int int0 = 2139;
      int int1 = (-1);
      // Undeclared exception!
      try { 
        board0.getCell(2139, 2139);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2139, 2139) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      int int0 = (-369);
      Board board0 = null;
      try {
        board0 = new Board((-369));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -369
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell((-2528), (-2528));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2528, -2528) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board board0 = new Board(981L);
      board0.toString();
      int int0 = Board.WINNING_VALUE;
      assertEquals(2048, int0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.moveUp();
      assertTrue(boolean0);
      
      board0.hasEmptyCells();
      boolean boolean1 = board0.hasEmptyCells();
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(boolean1);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board(1252L);
      board0.moveDown();
      board0.hasEmptyCells();
      board0.hashCode();
      board0.hashCode();
      board0.moveDown();
      Board.Direction[] board_DirectionArray0 = Board.Direction.values();
      assertEquals(4, board_DirectionArray0.length);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2295, 2295);
      boolean boolean0 = board_Position0.equals("&joW{1y__%5");
      assertEquals(2295, board_Position0.col);
      assertEquals(2295, board_Position0.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      boolean boolean1 = board0.moveRight();
      assertEquals(4, board0.getSize());
      assertFalse(boolean1 == boolean0);
      assertTrue(boolean1);
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Board board0 = new Board(981L);
      int int0 = board0.getScore();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1073));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1073
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveRight();
      board0.getEmptyPositions();
      board0.isFull();
      board0.isFull();
      board0.isFull();
      board0.isFull();
      board0.toString();
      board0.repOk();
      board0.moveLeft();
      board0.moveUp();
      board0.hasEmptyCells();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.toString();
      board0.isLosingBoard();
      Board.Direction.values();
      board0.toString();
      board0.getSize();
      board0.isLosingBoard();
      board0.moveDown();
      boolean boolean0 = board0.repOk();
      assertEquals(8, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board(2);
      board0.getEmptyPositions();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.moveRight();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.repOk();
      board0.moveRight();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("A(iD'I]<>>>.q{");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.A(iD'I]<>>>.q{
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Board board0 = new Board((-1L));
      board0.isWinningBoard();
      board0.toString();
      board0.isFull();
      board0.isWinningBoard();
      int int0 = 0;
      board0.getEmptyPositions();
      board0.moveDown();
      board0.moveLeft();
      // Undeclared exception!
      try { 
        board0.getCell(0, (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      int int0 = (-4796);
      Board.Position board_Position0 = new Board.Position((-4796), (-4796));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals(board_Position0);
      Board board0 = null;
      try {
        board0 = new Board((-4796));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -4796
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Board board0 = new Board();
      board0.getScore();
      Board board1 = new Board(board0);
      // Undeclared exception!
      try { 
        board1.setCell(1, 1, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      board0.isFull();
      board0.isLosingBoard();
      board0.moveUp();
      board0.moveUp();
      board0.hashCode();
      board0.moveDown();
      board0.toString();
      board0.moveDown();
      board0.hashCode();
      board0.isLosingBoard();
      board0.moveUp();
      board0.hashCode();
      board0.isFull();
      board0.moveUp();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(3169, 3169, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3169, 3169) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      board0.moveRight();
      board0.toString();
      board0.isFull();
      board0.isLosingBoard();
      board0.hasEmptyCells();
      board0.isFull();
      board0.moveDown();
      board0.toString();
      board0.repOk();
      Board.Direction.values();
      // Undeclared exception!
      try { 
        board0.getCell(4, (-12));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, -12) is out of bounds for board size 1
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Board board0 = new Board(1);
      board0.toString();
      boolean boolean0 = board0.moveRight();
      assertFalse(boolean0);
      
      Board board1 = new Board(board0);
      board1.toString();
      board1.hasEmptyCells();
      board1.hashCode();
      board0.hasEmptyCells();
      boolean boolean1 = board1.isWinningBoard();
      String string0 = board1.toString();
      assertEquals("Score: 0\n+-----+\n|    2|\n+-----+\n", string0);
      
      boolean boolean2 = board1.moveLeft();
      assertFalse(boolean2);
      
      boolean boolean3 = board1.isLosingBoard();
      assertTrue(boolean3);
      
      board1.isWinningBoard();
      boolean boolean4 = board0.moveDown();
      assertTrue(boolean4 == boolean1);
      
      Board.Position board_Position0 = new Board.Position((-4133), 2437);
      Board.Position board_Position1 = new Board.Position((-4133), 2082);
      boolean boolean5 = board_Position0.equals(board_Position1);
      assertTrue(boolean5 == boolean4);
      assertFalse(boolean5);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Board board0 = new Board();
      int int0 = (-1687);
      // Undeclared exception!
      try { 
        board0.getCell(3, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Board board0 = new Board((-699L));
      board0.hasEmptyCells();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.moveDown();
      board0.equals((Object) null);
      board0.moveLeft();
      Board.Position board_Position0 = new Board.Position(1088, 4);
      board_Position0.toString();
      board_Position0.toString();
      board0.getEmptyPositions();
      board_Position0.toString();
      board_Position0.equals(board0);
      board0.moveLeft();
      board0.repOk();
      board0.getScore();
      board0.isWinningBoard();
      board0.equals("(1088, 4)");
      board0.hashCode();
      board0.isFull();
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.moveRight();
      board0.isFull();
      board0.hashCode();
      board0.equals(set0);
      board0.equals("(1088, 4)");
      board_Position0.toString();
      board0.hashCode();
      board0.toString();
      board_Position0.toString();
      board0.isWinningBoard();
      assertEquals(8, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Board board0 = new Board();
      board0.isFull();
      board0.getEmptyPositions();
      board0.toString();
      Cell cell0 = new Cell(2048);
      board0.moveUp();
      board0.setCell(2, 2, cell0);
      board0.moveDown();
      board0.moveUp();
      board0.isFull();
      Object object0 = new Object();
      board0.isFull();
      board0.equals(object0);
      board0.isFull();
      board0.toString();
      board0.moveLeft();
      board0.isLosingBoard();
      board0.moveRight();
      Board.Position board_Position0 = new Board.Position(2, (-2));
      board_Position0.equals((Object) null);
      board0.hasEmptyCells();
      board0.getCell(2, 2);
      board0.moveLeft();
      board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.getSize();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(12, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Board board0 = new Board(0L);
      board0.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(4, 810);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board.Position board_Position1 = new Board.Position(810, 810);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      board0.moveLeft();
      // Undeclared exception!
      try { 
        board0.getCell((-1276), 3927);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1276, 3927) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }
}
